# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, max_length=20)),
                ('approver_field', models.CharField(blank=True, max_length=20)),
                ('about', models.TextField()),
                ('user_type', models.CharField(choices=[('WORKER2', 'Worker2'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'admin'), ('WORKER1', 'Worker1'), ('APPROVER2', 'Approver2'), ('APPROVER1', 'Approver1')], default='WORKER1', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
